name: Submit Game
description: Submit a request to add your game!
title: "[New Game] <Game Name>"

labels: ["publish this game plz", "needs approval"]

body:
- type: input
  id: id
  attributes:
    label: Game ID (e.g., io.github.amnoshield.RecycledCybernetics)
  validations:
    required: true

- type: input
  id: file_name
  attributes:
    label: File name (ie. Recycled_Cybernetics_linux.x86_64)
  validations:
    required: true

- type: input
  id: source_url
  attributes:
    label: Github release tarball URL
  validations:
    required: true

- type: input
  id: sha256
  attributes:
    label: SHA256 of source
  validations:
    required: true

- type: checkboxes
  id: idk-man
  attributes:
    label: idk man
    description: more then one may be selected
    options:
      - label: this should be required
      - required: true
      - label: testing
