name: Submit Game
description: Submit a request to add your game!
title: "[New Game] <Game Name>"

labels: ["publish this game plz", "needs approval"]

body:
- type: input
  id: id
  attributes:
    label: Game ID (e.g., io.github.amnoshield.RecycledCybernetics)
  validations:
    required: true

- type: input
  id: file_name
  attributes:
    label: File name (e.g., Recycled_Cybernetics_linux.x86_64)
  validations:
    required: true

- type: input
  id: source_url
  attributes:
    label: Github release tarball URL
  validations:
    required: true

- type: input
  id: sha256
  attributes:
    label: SHA256 of source
  validations:
    required: true

- type: checkboxes
  id: license-agreements
  attributes:
    label: idk man
    description: more then one may be selected
    options:
      - type: markdown
        attributes:
          value: "## idk if this will work"
      - label: The provided file(s) follow the specified format.
        required: true
      - label: The provided game executable is for Linux and not for Windows (e.g., some_game.exe), Apple/Mac, or any other operating system.
        required: true
